language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t aswwsa/docker-react -f Dockerfile.dev . 

script:
    - docker run -e CI=true aswwsa/docker-react npm run test -- --coverage